# Generated by Django 5.0 on 2025-04-01 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_userprofile_leaderboardentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trades', to='trading.userprofile'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trades', to='trading.userprofile'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
