# Generated by Django 5.0 on 2025-04-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_remove_userprofile_favorites_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owned_pokemon',
            field=models.ManyToManyField(blank=True, related_name='owners', to='trading.pokemon'),
        ),
    ]
