# Generated by Django 5.1.6 on 2025-04-22 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0005_pokemon_price_userprofile_owned_pokemon"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="experience_level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="trade",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="trading.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="owned_pokemon",
            field=models.ManyToManyField(blank=True, to="trading.pokemon"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist",
                to="trading.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="ForSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("listed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.pokemon",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trade",
            name="pokemon_offered",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades_offered",
                to="trading.pokemon",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="pokemon_requested",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades_requested",
                to="trading.pokemon",
            ),
        ),
    ]
