# Generated by Django 5.1.6 on 2025-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0006_remove_trade_status_remove_userprofile_wishlist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
    ]
