# Generated by Django 5.1.6 on 2025-04-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0007_remove_trade_status_remove_userprofile_wishlist_and_more"),
    ]

    operations = [
      migrations.RemoveField(
            model_name="userprofile",
            name="favorite_pokemon",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_pokemon",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="trading.pokemon"
            ),
        ),
    ]
